name: bookverse
description: A beautiful book discovery app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.2
  firebase_auth: ^4.6.1
  firebase_storage: ^11.2.1
  google_sign_in: ^5.4.0
  shimmer: ^2.0.0
  lottie: ^2.3.2
  flutter_neumorphic: ^3.2.0
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.0
  percent_indicator: ^4.2.2
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
